name: Build and generate artifacts for Bahmni Core

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
        server-username: GITHUB_USER_REF  
        server-password: GITHUB_TOKEN_REF
    - name: Install compass
      run: |
        sudo apt-get install ruby-dev
        sudo gem install compass -v 1.0.3
    - name: Build with Maven
      run: |
        mvn clean package -U -DattachMuleSources -Pgithub deploy
      env:
          GITHUB_USER_REF: ${{ secrets.DOCKER_HUB_USERNAME }}
          GITHUB_TOKEN_REF: ${{ secrets.GITHUB_TOKEN }}
        
